FROM node:16.20.2-alpine3.18

USER node

RUN mkdir -p /home/node/app

WORKDIR /home/node/app

COPY --chown=node:node package.json .

RUN yarn install

COPY --chown=node:node . .

CMD ["yarn", "start"]