name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.dev --tag timbilt/docker-react
    - name: Run unit tests
      run: docker run -e CI=true timbilt/docker-react yarn test
    - name: Generate deployment package
      run: zip -r deploy.zip . -x '*.git*'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v18
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
        aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
        application_name: "Docker React"
        environment_name: DockerReact-env
        existing_bucket_name: elasticbeanstalk-us-east-1-268277632823
        region: us-east-1
        version_label: ${{ github.sha }}
        deployment_package: deploy.zip

        
        
